### ISSUE TITLE
我调用异步IOHIDDeviceSetReportWithCallback 电脑重启 是什么鬼

### ISSUE THREAD

**Issue by tangzhifengjluzh** [czl0325/pebble#2]
因为如果调用同步的方法 IOHIDDeviceSetReport向设备写数据  设备返回也是在主线程，这样会有一个问题，当我在持续操作界面时，比如拖动滚动条。这样会阻塞 数据的回调，因为都在主线程。
所以我试图用异步的写方法 IOHIDDeviceSetReportWithCallback 但是调用他的话，电脑必然重启。

**Comment by czl0325** [comment]
怎么解决的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhifeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 中午1:44
收件人:&nbsp;"czl0325/pebble"<pebble@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [czl0325/pebble] 我调用异步IOHIDDeviceSetReportWithCallback 电脑重启 是什么鬼 (#2)




Closed #2.

**Comment by tangzhifengjluzh** [comment]
还是调用IOHIDDeviceSetReport 来写入数据到设备
 只是主线程换个runloop就好了
IOHIDManagerScheduleWithRunLoop(managerRef, CFRunLoopGetMain(), kCFRunLoopCommonModes);//kCFRunLoopDefaultMode

把kCFRunLoopDefaultMode 换成kCFRunLoopCommonModes 就完美解决了。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈昭良"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午4:06
收件人:&nbsp;"czl0325/pebble"<pebble@noreply.github.com&gt;;
抄送:&nbsp;"あ雨后天ぬ"<330200387@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [czl0325/pebble] 我调用异步IOHIDDeviceSetReportWithCallback 电脑重启 是什么鬼 (#2)



怎么解决的？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"zhifeng"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月25日(星期一) 中午1:44 
 收件人:&amp;nbsp;"czl0325/pebble"<pebble@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [czl0325/pebble] 我调用异步IOHIDDeviceSetReportWithCallback 电脑重启 是什么鬼 (#2) 
 
 
 
 
 Closed #2.
